name: Zip Files

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install zip
      run: sudo apt-get install zip

    - name: Create GitHub Release
      uses: pipe-cd/actions-gh-release@v2.6.0
      with:
          release_file: 'sctime.zip', 'sctime.xpi'
          token: ${{ secrets.GITHUB_TOKEN }}
            
            
