name: Zip Files

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install zip
      run: sudo apt-get install zip

    - name: Get latest release tag
      id: get_latest_tag
      run: |
        echo ::set-output name=TAG::$(git describe --tags `git rev-list --tags --max-count=1`)

    - name: Increment version
      id: increment_version
      run: |
        # Extract the numeric part of the tag
        VERSION=${{ steps.get_latest_tag.outputs.TAG#v }}
        # Increment the version by 1
        VERSION=$((VERSION + 1))
        echo "::set-output name=NEW_VERSION::v${VERSION}"

    - name: Zip files
      run: |
        zip sctime.zip extension.js manifest.json
        mv manifestfirefox.json manifest.json
        zip sctime.xpi extension.js manifest.json
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.increment_version.outputs.NEW_VERSION }}
        release_name: Release ${{ steps.increment_version.outputs.NEW_VERSION }}
        body: Automatic release by Github Actions Workflow
        draft: false
        prerelease: true
