name: Zip Files

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install zip
      run: sudo apt-get install zip

    - name: Get latest release tag
      id: get_latest_tag
      run: |
        echo ::set-output name=TAG::$(git describe --tags --abbrev=0)

    - name: Increment version
      id: increment_version
      run: |
        # Extract the numeric part of the tag
        VERSION=$(echo "${{ steps.get_latest_tag.outputs.TAG }}" | sed 's/v//')
        # Increment the version by 1
        VERSION=$((VERSION + 1))
        echo "::set-output name=NEW_VERSION::v${VERSION}"

    - name: Zip files
      run: |
        zip sctime.zip extension.js manifest.json
        mv manifestfirefox.json manifest.json
        zip sctime.xpi extension.js manifest.json

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.increment_version.outputs.NEW_VERSION }}
        release_name: ${{ steps.increment_version.outputs.NEW_VERSION }}
        body: Automatic Release
        draft: false
        prerelease: true

    - name: Upload Files
      uses: actions/upload-artifact@v2
      with:
        name: release-assets
        path: |
            sctime.zip
            sctime.xpi
            
            
