name: Zip Files

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install zip
      run: sudo apt-get install zip

    - name: Zip files
      run: |
        zip sctime.zip extension.js manifest.json
        mv manifestfirefox.json manifest.json
        zip sctime.xpi extension.js manifest.json
        
    - name: Upload To Github Release
      uses: xresloader/upload-to-github-release@v1.5.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "*sctime.zip, sctime.xpi"
        tags: true
        draft: true
        prerelease: true
            
